# Generated by Django 3.2.9 on 2021-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='origen',
            field=models.CharField(max_length=100, verbose_name='Origen'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ingredientes', models.ManyToManyField(to='menu.Ingrediente', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Receta',
            },
        ),
    ]
