# Generated by Django 3.2.9 on 2021-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211122_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='valor',
            field=models.CharField(max_length=100, null=True, verbose_name='ValorNutricional'),
        ),
    ]
