# Generated by Django 3.2.9 on 2021-11-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_ingrediente_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='valor',
            field=models.IntegerField(null=True, verbose_name='ValorNutricional'),
        ),
    ]
