# Generated by Django 3.2.9 on 2021-11-23 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0004_alter_ingrediente_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='valor',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='alergeno',
            field=models.CharField(blank=True, max_length=100, verbose_name='alergeno'),
        ),
        migrations.AddField(
            model_name='receta',
            name='valor',
            field=models.IntegerField(null=True, verbose_name='Valor nutricional'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del comensal')),
                ('alergia', models.ManyToManyField(to='menu.Ingrediente', verbose_name='Alergias del comensal')),
                ('plato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.receta', verbose_name='Plato favorito')),
            ],
            options={
                'verbose_name': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('file', models.ImageField(height_field='alto', upload_to='imagenes/%Y/%m/%d/', verbose_name='imagen', width_field='ancho')),
                ('ancho', models.IntegerField(default=0, editable=False)),
                ('alto', models.IntegerField(default=0, editable=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Fecha de subida')),
                ('subida_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subida por usuario')),
            ],
        ),
    ]
