# Generated by Django 3.2.9 on 2021-11-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20211123_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='valor',
        ),
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/Receta'),
        ),
    ]
