# Generated by Django 3.2.9 on 2021-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20211126_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/static/img/Receta'),
        ),
    ]
