# Generated by Django 3.2.9 on 2021-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20211127_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alergia',
            options={'verbose_name': 'Alergia'},
        ),
        migrations.RemoveField(
            model_name='alergia',
            name='plato',
        ),
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/static/img'),
        ),
    ]
