# Generated by Django 3.2.9 on 2021-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20211127_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='origen',
            field=models.CharField(choices=[('An', 'Animal'), ('Ve', 'Vegetal'), ('De', 'Derivado')], max_length=100, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/static/img'),
        ),
    ]
