# Generated by Django 3.2.9 on 2021-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20211127_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/ingredientes'),
        ),
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/recetas'),
        ),
        migrations.DeleteModel(
            name='ImgIngre',
        ),
        migrations.DeleteModel(
            name='ImgReceta',
        ),
    ]
