# Generated by Django 3.2.9 on 2021-11-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_auto_20211128_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alergia',
            name='alergeno',
        ),
        migrations.AddField(
            model_name='alergia',
            name='alergeno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingrediente', verbose_name='Ingredientes alergeno'),
        ),
    ]
